### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by Norton73**
Added code of conduct to the root.

### CODE REVIEW

**Comment by TalAter** [comment]
Hi @Norton73, thank you for taking the time to contribute to open source.

Can you explain the need for this pull request? There already is a code of conduct document, which you replaced with a different one. Why do you believe we need to change from a markdown to a plaintext file?

Thanks again.

**Comment by Norton73** [comment]
Hi Tal,

Sorry about that. I was following the instructions. I am a bit new to github.

I will reset my fork and be more careful in the future.

Best regards,

Aaron

**Comment by TalAter** [comment]
No problem @Norton73 

There's no real magic to contributing to open-source other than working at it and being very meticulous. I always make sure to nitpick my own code, going over every line I changed a 2nd and 3rd time, before sending any pull requests.

Feel free to pick up any of the other open first-timer issues.

**Comment by Norton73** [comment]
Hi Tal,

Thanks for the advice.

Cheers,

Aaron

**Pull request closed without merging**
