### PR TITLE
Add tests for issue #31 #27 #28 (testing randomMissionsCompleted func)

### PR DESCRIPTION
**Pull request by malltshik**
Add some tests for randomMissionsCompleted().
I was never write tests by jest (for nodejs applications) before that moment.
Verify my code, please.

### CODE REVIEW

**Comment by malltshik** [comment]
In issues nothing says about 4 and 90 numbers for tests.
I think that's not good idea expect this numbers because today we need 4 and 90, but tomorrow it's 5 and over 99999.

**Comment by TalAter** [comment]
Hi @malltshik,

Thanks for taking on so many issues!

We create these *first-timer-only* issues as a way for people who have never contributed to open-source to try their first pull request.

It actually takes a lot more time to write these issues than it would have for us to simply solve them ourselves, but we do that (and @cg-cnu has been doing a lot of hard work to accomplish this) as a way to give many new people a chance to get involved with open source for the first time.

And I think this method works great as a way to make open-source more inviting. It has obviously succeeded in giving you a lot of enthusiasm to contribute, as can be seen by this pull request 😃 

Unfortunately, when you close 3 issues at once like this, we are missing out on an opportunity for 3 other people to make their first ever pull request.

As I mentioned in the past, these issues are not about solving a hard programming challenge, but about doing something new for the first time. The programming challenge here is nothing for you, and you have already contributed in the past, so why not move up to the next level now? Find an issue that isn't marked for *first-timers-only*, or find something which you think needs improving, and help us with that.

Thank you again for the enthusiasm, and spending time on helping. We really do appreciate it, and I hope you understand.

**Comment by malltshik** [comment]
Oh, I'm sorry!
I did not immediately understand the purpose of these issues. I just started solving them :)
What you do is great stuff! Thank you! 

I will look for other issues in a real project!

**Comment by TalAter** [comment]
Thank you for understanding @malltshik.

I'm glad the open-source spirit is so strong within you! 👍

By the way, this is a real project. We are building [real technology](https://dav.network/) and open sourcing all that we do. It's just the issues labeled `first-timers-only` that are focused on helping beginners. We definitely could use your help with any other improvements.

**Pull request closed without merging**
