### PR TITLE
Issue #102: Replace hardcoded value

### PR DESCRIPTION
**Pull request by Peachball**
Replaced a hardcoded number with a call to the config file.
## Description

Replaced a magic number in server/store/requests.js with a call to server/config/index.js

## Related Issue

[Issue](https://github.com/DAVFoundation/missioncontrol/issues/102)

## Motivation and Context

Placing constants in a config file makes the code more maintainable, and easier to refactor.

## How Has This Been Tested?

The changes pass the tests, and do not break the server. When the ttl was printed to the console,
it matched the expected result of 43200.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TalAter** [comment]
Hi @Peachball,

Thank you for taking the time to contribute to open source :octocat: 

Your code looks great. One comment though, there is another instance of that hardcoded value further down in the same file on line 30 (https://github.com/Peachball/missioncontrol/blob/386bd63f8d21fde74018815d410179758f5241cf/server/store/requests.js#L30). Can you replace that one as well?

👍

**Comment by TalAter** [comment]
One more thing

`require('../config/index.js');` can actually be shortened to `require('../config');`
Node.js assumes `index.js` automatically.

**Comment by Peachball** [comment]
I've changed the require and the other hardcoded value.

**Comment by TalAter** [comment]
Thank you so much @Peachball 
And congratulations on joining the world of open source 🍾 

Please join us in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) where we discuss DAV, and more opportunities to get involved with open source :octocat:

**Pull request merged**
