### PR TITLE
removed davAddress parameter from the function getDavIdIconUrl

### PR DESCRIPTION
**Pull request by cg-cnu**
very small cleanup 😄

### CODE REVIEW

**Comment by TalAter** [comment]
That one was actually there on purpose preparing for a future improvement.

In the future `getDavIdIconUrl()` will receive a DAV ID as an argument and return an icon url for that DAV user. In preparation, I am passing DAV ID to it always

**Comment by cg-cnu** [comment]
@TalAter Sorry, didn't know that! Will check with out before pr in future 🙂

**Comment by TalAter** [comment]
No worries. It was my fault... I kept too much knowledge in my brain without properly documenting.

If you're looking to help with this one, here's something that can be helpful.

- Expand the `getDavIdIconUrl()` function to receive a `davId` argument, and return `https://lorempixel.com/100/100/abstract/?${davId}`
- Further expand that function so that it throws an exception if no `davId` is passed to it.
- Make sure everywhere we call that function we didn't forget to pass `davId`
- Add JSDoc documentation to that function.
- Update the test that calls it to make sure it passes a davId to it (can just be a string, no need to require the function that generates random ids there).
- Create an issue for first timers to add a test to verify that it throws an exception when no davId is passed.

**Comment by TalAter** [comment]
@cg-cnu Created #61

**Pull request closed without merging**
