### PR TITLE
Issue #111 - Ensure status of vehicle is available before creating a bid with that…

### PR DESCRIPTION
**Pull request by bicep**
Added an if condition to check if vehicle status is available before going on to add the vehicle to a new bid.

### CODE REVIEW

**Comment by TalAter** [comment]
Now that I'm looking at this issue again, it is a bit more complicated than I originally thought.
Mostly because of the [hacky way](https://github.com/bicep/missioncontrol/blob/26d8203b032e553f964ea7404255351db482f204/server/store/bids.js#L65) I am choosing the vehicles to create bids from.
The way you changed the code, once it reaches a vehicle that isn't available it won't create any new bids (it will just keep trying that same vehicle every time status is called).

May I suggest changing it so that if a vehicle is not available, we'll add a new vehicle to the simulated environment and make a bid from that vehicle. That is an acceptable solution to make sure we always have enough vehicles in the simulated environment... in essence we are creating a simulation of an environment where new service providers come in with new drones to keep up with demand. Once the number of drones in an area is enough to keep up, new ones will no longer need to be created.

When a vehicle isn't available you can use `generateAndAddVehicles()` to generate a new vehicle. You'll have to export it from `server/store/vehicles`.

**Comment by bicep** [comment]
Thanks for taking the time to reply. Let me work on this and send another PR!
Is this a correct representation of what happens when there are not enough vehicles?
And then if there are less than 10 bids, then we make some bids up. We find vehicles that are near the need using `georadiusAsync` in line 57, and only if there are more vehicles than bids, then we create a new bid with a random vehicle. Doesn't this mean there is essentially only one vehicle?

**Comment by TalAter** [comment]
Only one bid is added at a time. This is by design, so bids come in over time.

But they don't actually come from a random vehicle. They come from the x vehicle in the list, x being how many bids we already have. This has been a good fast trade off in the simulation, but is a bit hacky. Thing is, when your saw that vehicle wasn't available and just didn't create a new bid, next time it would try the same vehicle over and over again.

**Comment by TalAter** [comment]
Is this ready for review?

**Comment by bicep** [comment]
Yes! I'll rebase with master and squash the commits if you give the green light. 
The code works as expected if you change the random (drone) vehicle status to unavailable.

**Comment by TalAter** [comment]
Looks good!
Thanks for the help @bicep !

**Pull request merged**
